version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    volumes:
      - .:/app:z
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - "8000"
    ports:
      - 8000:8000
    env_file:
      - .envs/.local/.docker
      - .envs/.local/.postgres
    depends_on:
      - postgres
      - mailhog
      # - redis
    command: /start
    networks:
      - medium-scribe-api
  
  postgres:
    build:
      context: .
      dockerfile: ./docker/local/postgres/Dockerfile
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - medium-scribe-api

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025"
    networks:
      - medium-scribe-api

  # redis:
  #   image: redis:7-alpine
  #   networks:
  #     - medium-scribe-api
  
  # celery-worker:
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-celeryworker
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.envs/.local/.docker
  #     - ./.envs/.local/.postgres
  #   depends_on:
  #     - redis
  #     - postgres
  #     - mailhog
  #   networks:
  #     - medium-scribe-api

  # flower:
  #   build:
  #     context: .
  #     dockerfile: ./docker/local/django/Dockerfile
  #   command: /start-flower
  #   volumes:
  #     - flower_data:/data
  #   env_file:
  #     - ./.envs/.local/.docker
  #     - ./.envs/.local/.postgres
  #   ports:
  #     - "5555:5555"
  #   depends_on:
  #     - "redis"
  #     - "postgres"
  #   networks:
  #     - medium-scribe-api

  # nginx:
  #   build:
  #     context: . # define the root for the build
  #     dockerfile: ./docker/local/nginx/Dockerfile
  #   restart: always
  #   depends_on:
  #     - api
  #   volumes:
  #     - static_volume:/app/staticfiles
  #     - media_volume:/app/mediafiles
  #   ports:
  #     - "8080:80"
  #   networks:
  #     - medium-scribe-api

networks:
  medium-scribe-api:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  flower_data: {}